/**
 * PwaStatus — what the installed-app machinery has to say, in three small notes.
 *
 *   "Ready to work offline"   the first time everything has been stored
 *   "A new version is ready"  with a Reload button, never an automatic reload:
 *                             someone may be in the middle of a sentence
 *   "You are offline"         a quiet chip while there is no connection
 *
 * The service worker itself is generated by vite-plugin-pwa (vite.config.js).
 * It only exists in a production build; in `npm run dev` this component
 * registers nothing and shows only the offline chip.
 */
import { useEffect, useState } from 'react';
import { useRegisterSW } from 'virtual:pwa-register/react';
import { CloudOff, RefreshCw, Wifi, X } from 'lucide-react';
import './pwa-status.css';

const CHECK_FOR_UPDATE_MS = 60 * 60 * 1000; // once an hour while the app stays open

const BACK_ONLINE_MS = 4000;

/** Is there a connection, and did it only just come back? */
function useOnline() {
  const [online, setOnline] = useState(() => navigator.onLine);
  const [backOnline, setBackOnline] = useState(false);
  useEffect(() => {
    let timer;
    const on = () => {
      setOnline(true);
      setBackOnline(true);
      window.clearTimeout(timer);
      timer = window.setTimeout(() => setBackOnline(false), BACK_ONLINE_MS);
    };
    const off = () => {
      window.clearTimeout(timer);
      setBackOnline(false);
      setOnline(false);
    };
    window.addEventListener('online', on);
    window.addEventListener('offline', off);
    return () => {
      window.clearTimeout(timer);
      window.removeEventListener('online', on);
      window.removeEventListener('offline', off);
    };
  }, []);
  return { online, backOnline };
}

export default function PwaStatus() {
  const { online, backOnline } = useOnline();
  const {
    offlineReady: [offlineReady, setOfflineReady],
    needRefresh: [needRefresh, setNeedRefresh],
    updateServiceWorker,
  } = useRegisterSW({
    onRegisteredSW(_url, registration) {
      if (registration) window.setInterval(() => registration.update().catch(() => {}), CHECK_FOR_UPDATE_MS);
    },
  });

  // "Ready to work offline" is good news, not a task: let it go by itself.
  useEffect(() => {
    if (!offlineReady) return undefined;
    const timer = window.setTimeout(() => setOfflineReady(false), 6000);
    return () => window.clearTimeout(timer);
  }, [offlineReady, setOfflineReady]);

  return (
    <div className="pwa-stack" aria-live="polite">
      {!online && (
        <p className="pwa-chip" role="status">
          <CloudOff size={14} /> You are offline. Your documents are safe on this device.
        </p>
      )}

      {online && backOnline && (
        <p className="pwa-chip pwa-chip-good" role="status">
          <Wifi size={14} /> Back online.
        </p>
      )}

      {needRefresh && (
        <div className="pwa-card" role="status">
          <span>A new version of DocuMend is ready.</span>
          <button type="button" className="pwa-primary" onClick={() => updateServiceWorker(true)}>
            <RefreshCw size={13} /> Reload
          </button>
          <button type="button" className="pwa-close" onClick={() => setNeedRefresh(false)} aria-label="Later">
            <X size={14} />
          </button>
        </div>
      )}

      {offlineReady && (
        <div className="pwa-card" role="status">
          <span>DocuMend is ready to work offline.</span>
          <button type="button" className="pwa-close" onClick={() => setOfflineReady(false)} aria-label="Dismiss">
            <X size={14} />
          </button>
        </div>
      )}
    </div>
  );
}
